name: Test site 389
favicon: null
layout_spectrum: 0.5788531
typography_spectrum: 1
title: This is not artificial intelligence
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010403'
    - '#4B775B'
    - '#FFC602'
    - '#FB015C'
    - '#FFE0B4'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
