name: Test site 389
favicon: null
layout_spectrum: 0.48625
typography_spectrum: 0.43079
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: This is not artificial intelligence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#014202'
    - '#FFE9FA'
    - '#89C588'
    - '#FFE801'
    - '#FF01E0'
  brandStrength: 0.5084317
  lightness: 0.2221111212857068
  saturation: 0.05122892186045647
  rhythmicContrast: 0.515986789483577
purpose: []
