layout_spectrum: 0.48625
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.05122892186045647
  lightness: 0.2221111212857068
  brandStrength: 0.5084317
  brandColors:
    - '#014202'
    - '#FFE9FA'
    - '#89C588'
    - '#FFE801'
    - '#FF01E0'
  rhythmicContrast: 0.515986789483577
typography_spectrum: 0.43079
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Test site 389
